name: Reorder Support Pipeline

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'The branch to rename to main must start with "reorder/"'
        required: true

jobs:
  set-var:
    name: Set Variable for inputs target_branch
    runs-on: [self-hosted, Linux, x64, paper-backend]
    outputs: 
      target_branch: ${{ steps.set-target_branch.outputs.target_branch }}
    steps: 
        - id: set-target_branch
          name: Set value for target_branch
          run: echo "target_branch=${{ github.event.inputs.target_branch }}" >> $GITHUB_OUTPUT
  rename-branch:
    uses: paper-indonesia/paper-devops/.github/workflows/reorder-rename-branch.yml@master
    secrets: inherit
    needs: set-var
    with: 
      target_branch: ${{ needs.set-var.outputs.target_branch }}